name: benrush
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#35343a'
    - '#a59c9d'
    - '#776c66'
    - '#942021'
    - '#b84b2a'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
